import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../../components/Navbar"
import Hero from "../../components/Hero"
import About from 'components/About'
import Bitacora from 'components/Bitacora'
import Bitacora2 from 'components/Bitacora2'
import Bitacora3 from 'components/Bitacora3'
import Titulo from 'components/Titulo'
import Arduino from 'components/Arduino'





export default function Home() {
  return (
    <div>
      <Head>
        <title>bitacora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <Hero />
        <About />
        <Titulo/>
        <Arduino/>
        <Bitacora />
        <Bitacora2/>
        <Bitacora3/>

      </main>
    </div>
  )
}
